### ISSUE TITLE
Reproducibility failing when passing seed in MultiThreadedNS

### ISSUE THREAD

**Issue by dreyes17** [BEAST2-Dev/nested-sampling#11]
Hello,

I am trying to reproduce the same results using beast -seed 1 in all my executions but I am not being able to do it when using MultiThreadedNS.

This is not the case when using simple NS. The only thing I could find about this is in the beast.util.Randomizer that they use the class MersenneTwisterFast that maybe is not doing it well with threads synchronization.

Best regards,

Daniel Reyes

**Comment by rbouckaert** [comment]
Hi Daniel, 

This is expected behaviour: the Randomizer class is deterministic, so when requests for random numbers are made to it *in the same order* it will produce exactly the same sequence of numbers in that order when starting from the same seed. However, when running multiple threads, the order in which Randomizer is asked to produce random numbers can vary because threads can run a bit slower or faster, depending on how much time these threads get allocated. Therefore, the behaviour can vary a little, and runs starting with the same seed do not necessarily produce exactly the same result. In other words, threading introduces another source of randomness.

I am not sure how to guarantee deterministic behaviour, unless threads manage their own Randomizer -- implementing this seems non-trivial though. Usually, we are more concerned making the behaviour more random, not less.

Cheers,
Remco

**Comment by dreyes17** [comment]
Thank you very much! ok I understand that maybe is not trivial or even is unnecessary.

A possible solution could be as you say having a Randomizer per thread with a seed = seed sended by parameter + index of the thread. In this way thread 0, should have a seed0 = seed + 0, thread 1: seed1 = seed + 1. And in this way ensure each solution is different from the others.

Cheers,

Daniel
